### ISSUE TITLE
Unable to build on windows with GNU toolchain

### ISSUE THREAD

**Issue by njasm** [Lakelezz/audiopus_sys#5]
Hello,

I'm unable to build on windows with the GNU toolchain. 
this crate is used on the serenity dependency my project have.

If I change toolchain to msvc it builds, but that toolchain is not an option :( even in Windows environment.

rustup show 
```bash
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Nelson Morais\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

x86_64-pc-windows-gnu
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.40.0 (73528e339 2019-12-16)
```

```bash
...
   Compiling hyper v0.13.1
   Compiling hyper-tls v0.4.1
   Compiling audiopus_sys v0.1.5
error: failed to run custom build command for `audiopus_sys v0.1.5`
Caused by:
  process didn't exit successfully: `D:\Code\rust\m-bot\target\debug\build\audiopus_sys-b7750ffa84df77b7\build-script-build` (exit code: 101)
--- stdout
cargo:info=No feature or environment variable found, linking by default.
cargo:info=`pkg_config` could not find `Opus`.
cargo:info=Opus source path: "\\\\?\\C:\\Users\\Nelson Morais\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\audiopus_sys-0.1.5\\opus".
cargo:info=Opus will be built as static-library.
--- stderr
cp: cannot stat '\?\C:\Users\Nelson Morais\.cargo\registry\src\github.com-1ecc6299db9ec823\audiopus_sys-0.1.5\opus': No such file or directory
thread 'main' panicked at 'Failed to copy Opus files.', C:\Users\Nelson Morais\.cargo\registry\src\github.com-1ecc6299db9ec823\audiopus_sys-0.1.5\build.rs:69:9
stack backtrace:
```

**Comment by Lakelezz** [comment]
This is attempting to build for `v0.1.5`. 
Could you please perform `cargo clean` and `cargo update` to see if that solves this problem?

**Comment by njasm** [comment]
hello thanks for your fast reply.

I've tried it to clean and update.
With that, library version in bumped to 0.1.7 but have exact same error trying to "cp" on build.

`build.rs` assumes that if the target env is "GNU" then the code's compiling on a unix like environment, which clearly not true in this case.

```cmd
error: failed to run custom build command for `audiopus_sys v0.1.7`

Caused by:
  process didn't exit successfully: `D:\Code\rust\m-bot-test\target\debug\build\audiopus_sys-637a3ce65c193db4\build-script-build` (exit code: 101)
--- stdout
cargo:info=No feature or environment variable found, linking by default.
cargo:info=`pkg_config` could not find `Opus`.
cargo:info=Opus source path: "\\\\?\\C:\\Users\\Nelson Morais\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\audiopus_sys-0.1.7\\opus".
cargo:info=Opus will be built as static-library.

--- stderr
cp: cannot stat '\?\C:\Users\Nelson Morais\.cargo\registry\src\github.com-1ecc6299db9ec823\audiopus_sys-0.1.7\opus': No such file or directory
thread 'main' panicked at 'Failed to copy Opus files.', C:\Users\Nelson Morais\.cargo\registry\src\github.com-1ecc6299db9ec823\audiopus_sys-0.1.7\build.rs:90:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by Lakelezz** [comment]
Thanks for updating!

Window's GNU-toolchain requires MSYS2 for this crate, are you using MSYS2?

**Comment by njasm** [comment]
Hi,
No I was not using it. 

I dont have experience with it, so what i did was:
1) run the installer MSYS2
2) un-commented `MSYS2_PATH_TYPE=inherit` so to have cargo, rustup/rustc already in path for both mingw32 and 64 command lines.
3) executed the `cargo cleanb` and `cargo build` (thested on 32 and 64 version and the error is still the same.

Clearly i'm missing some steps here to have its compiled under MSYS2 console. 
Can you help me out on this? Thanks!

```bash
   Compiling parking_lot v0.9.0
   Compiling hyper v0.12.35
   Compiling audiopus_sys v0.1.7
   Compiling mime_guess v2.0.1
error: failed to run custom build command for `audiopus_sys v0.1.7`

Caused by:
  process didn't exit successfully: `D:\Code\rust\m-bot-test\target\debug\build\audiopus_sys-637a3ce65c193db4\build-script-build` (exit code: 101)
--- stdout
cargo:info=No feature or environment variable found, linking by default.
cargo:info=`pkg_config` could not find `Opus`.
cargo:info=Opus source path: "\\\\?\\C:\\Users\\Nelson Morais\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\audiopus_sys-0.1.7\\opus".
cargo:info=Opus will be built as static-library.

--- stderr
cp: cannot stat '\?\C:\Users\Nelson Morais\.cargo\registry\src\github.com-1ecc6299db9ec823\audiopus_sys-0.1.7\opus': No such file or directory
thread 'main' panicked at 'Failed to copy Opus files.', C:\Users\Nelson Morais\.cargo\registry\src\github.com-1ecc6299db9ec823\audiopus_sys-0.1.7\build.rs:90:9
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized

**Comment by njasm** [comment]
Thanks for the help @Lakelezz , I ended up using WSL and do the builds there. 

Thank you!
